export * from './App';
export { default as HomeTemplate } from './components/templates/HomeTemplate';
export * from './context/AuthContext';
export * from './main';
export {default as Home} from './pages/Home';
export * from './routers/routes';
export * from './styles/breackpoints';
export * from './styles/themes';
export * from './styles/variables';
export * from './supabase/supabase.config';
export * from './utils/dataEstatica';
